lib/firestorm_web/web/router.ex
defmodule FirestormWeb.Web.Router do
  use FirestormWeb.Web, :router

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", FirestormWeb.Web do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
    get "/logout", AuthController, :delete
  end

  scope "/", FirestormWeb.Web do
    pipe_through :browser # Use the default browser stack

    get "/", CategoryController, :index
    resources "/users", UserController
    resources "/categories", CategoryController do
      resources "/threads", ThreadController
    end
  end
end

lib/firestorm_web/web/controllers/category_controller.ex
defmodule FirestormWeb.Web.CategoryController do
  use FirestormWeb.Web, :controller

  alias FirestormWeb.Forums

  def index(conn, _params) do
    categories = Forums.list_categories()
    render(conn, "index.html", categories: categories)
  end

  def new(conn, _params) do
    changeset = Forums.change_category(%FirestormWeb.Forums.Category{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"category" => category_params}) do
    case Forums.create_category(category_params) do
      {:ok, category} ->
        conn
        |> put_flash(:info, "Category created successfully.")
        |> redirect(to: category_path(conn, :show, category))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    category =
      id
      |> Forums.get_category!
      |> FirestormWeb.Repo.preload(:threads)
    render(conn, "show.html", category: category)
  end

  def edit(conn, %{"id" => id}) do
    category = Forums.get_category!(id)
    changeset = Forums.change_category(category)
    render(conn, "edit.html", category: category, changeset: changeset)
  end

  def update(conn, %{"id" => id, "category" => category_params}) do
    category = Forums.get_category!(id)

    case Forums.update_category(category, category_params) do
      {:ok, category} ->
        conn
        |> put_flash(:info, "Category updated successfully.")
        |> redirect(to: category_path(conn, :show, category))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", category: category, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    category = Forums.get_category!(id)
    {:ok, _category} = Forums.delete_category(category)

    conn
    |> put_flash(:info, "Category deleted successfully.")
    |> redirect(to: category_path(conn, :index))
  end
end

lib/firestorm_web/web/views/category_view.ex
defmodule FirestormWeb.Web.CategoryView do
  use FirestormWeb.Web, :view

  def category_link(conn, category) do
    link category.title, to: category_path(conn, :show, category.id)
  end
end

lib/firestorm_web/web/templates/category/edit.html.eex
<h2>Edit Category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :update, @category) %>

<span><%= link "Back", to: category_path(@conn, :index) %></span>

lib/firestorm_web/web/templates/category/form.html.eex
<%= form_for @changeset, @action, [class: "new-category"], fn f -> %>
  <div>
    <label>
      Title: <%= text_input f, :title %>
      <%= error_tag f, :title %>
    </label>
  </div>

  <%= submit "Create Category", class: "pure-button button-primary" %>
<% end %>

lib/firestorm_web/web/templates/category/index.html.eex
<span><%= link "New Category", to: category_path(@conn, :new) %></span>

<ol class="category-list">
  <%= for category <- @categories do %>
    <li>
      <h2 class="title">
        <%= category_link(@conn, category) %>
      </h2>
    </li>
  <% end %>
</ol>

lib/firestorm_web/web/templates/category/new.html.eex
<h2>New Category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :create) %>

<span><%= link "Back", to: category_path(@conn, :index) %></span>

lib/firestorm_web/web/templates/category/show.html.eex
<div class="category-header">
  <h2><%= link @category.title, to: category_path(@conn, :show, @category) %></h2>
  <div class="spacer"></div>
  <ul class="actions">
    <li>
      <a class="pure-button button-primary" href="<%= category_thread_path(@conn, :new, @category) %>">
        <i class="fa fa-plus"></i>
        New Thread
      </a>
    </li>
  </ul>
</div>

<h3>Threads</h3>
<ol class="thread-list">
  <%= for thread <- @category.threads do %>
    <li class="thread-list-item">
      <div class="details">
        <div class="summary">
          <%= link thread.title, to: category_thread_path(@conn, :show, @category, thread), class: "title" %>
        </div>
        <div class="metadata">
          <%= thread.inserted_at %>
        </div>
      </div>
      <div class="supplemental">
        <div class="badge-block">1</div>
      </div>
    </li>
  <% end %>
</ol>

<span><%= link "Edit", to: category_path(@conn, :edit, @category) %></span>
<span><%= link "Back", to: category_path(@conn, :index) %></span>