lib/firestorm_web/web/router.ex
defmodule FirestormWeb.Web.Router do
  use FirestormWeb.Web, :router

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", FirestormWeb.Web do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
    get "/logout", AuthController, :delete
  end

  scope "/", FirestormWeb.Web do
    pipe_through :browser # Use the default browser stack

    get "/", CategoryController, :index
    resources "/users", UserController
    resources "/categories", CategoryController do
      resources "/threads", ThreadController
    end
  end
end

lib/firestorm_web/web/controllers/thread_controller.ex
defmodule FirestormWeb.Web.ThreadController do
  use FirestormWeb.Web, :controller

  alias FirestormWeb.Repo
  alias FirestormWeb.Forums
  alias FirestormWeb.Forums.Thread

  def action(conn, _) do
    category = Forums.get_category!(conn.params["category_id"])
    args = [conn, conn.params, category]
    apply(__MODULE__, action_name(conn), args)
  end

  def index(conn, _params, category) do
    threads = Forums.list_threads(category)
    render(conn, "index.html", threads: threads, category: category)
  end

  def new(conn, _params, category) do
    changeset =
      %Thread{category_id: category.id}
      |> Forums.change_thread
    render(conn, "new.html", changeset: changeset, category: category)
  end

  def create(conn, %{"thread" => thread_params}, category) do
    case Forums.create_thread(category, current_user(conn), %{title: thread_params["title"], body: thread_params["body"]}) do
      {:ok, thread} ->
        conn
        |> put_flash(:info, "Thread created successfully.")
        |> redirect(to: category_thread_path(conn, :show, category, thread))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, category: category)
    end
  end

  def show(conn, %{"id" => id}, category) do
    thread =
      Forums.get_thread!(category, id)
      |> Repo.preload(:posts)

    [ first_post | posts ] = thread.posts

    render(conn, "show.html", thread: thread, category: category, first_post: first_post, posts: posts)
  end

  def edit(conn, %{"id" => id}, category) do
    thread = Forums.get_thread!(category, id)
             |> Repo.preload(:posts)
    changeset = Forums.change_thread(thread)
    render(conn, "edit.html", thread: thread, changeset: changeset, category: category)
  end

  def update(conn, %{"id" => id, "thread" => thread_params}, category) do
    thread = Forums.get_thread!(category, id)

    case Forums.update_thread(thread, thread_params) do
      {:ok, thread} ->
        conn
        |> put_flash(:info, "Thread updated successfully.")
        |> redirect(to: category_thread_path(conn, :show, category, thread))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", thread: thread, changeset: changeset, category: category)
    end
  end

  def delete(conn, %{"id" => id}, category) do
    thread = Forums.get_thread!(category, id)
    {:ok, _thread} = Forums.delete_thread(thread)

    conn
    |> put_flash(:info, "Thread deleted successfully.")
    |> redirect(to: category_thread_path(conn, :index, category))
  end
end

lib/firestorm_web/web/views/thread_view.ex
defmodule FirestormWeb.Web.ThreadView do
  use FirestormWeb.Web, :view
  alias FirestormWeb.Markdown

  def markdown(body) do
    body
    |> Markdown.render
    |> raw
  end
end

lib/firestorm_web/web/templates/thread/_first_post.html.eex
<div class="post-item">
  <div class="body">
    <%= markdown(@post.body) %>
  </div>

  <div class="post-item-actions">
    <div class="reply-count">
      <%= length(@thread.posts) - 1 %> replies
    </div>
    <div class="spacer"></div>
    <ul class="actions">
      <li class="reaction">
        <a class="reaction-picker" href="#">
          <i class="emoticon-faces"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-eye"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-quote-right"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-reply"></i>
        </a>
      </li>
    </ul>
  </div>
</div>

lib/firestorm_web/web/templates/thread/_post.html.eex
<div class="post-item">
  <div class="item-metadata">
    <%= link "@some_user", to: "#", class: "username" %>
    <%= @post.inserted_at %>
  </div>

  <div class="body">
    <%= @post.body %>
  </div>

  <div class="post-item-actions">
    <div class="reactions">
      🦀
    </div>
    <div class="spacer"></div>
    <ul class="actions">
      <li>
        <a href="#">
          <i class="fa fa-link"></i>
        </a>
      </li>
      <li>
        <a class="reaction-picker" href="#">
          <i class="emoticon-faces"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-quote-right"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-reply"></i>
        </a>
      </li>
    </ul>
  </div>
</div>

lib/firestorm_web/web/templates/thread/edit.html.eex
<h2>Edit Thread</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_thread_path(@conn, :update, @category, @thread) %>

<span><%= link "Back", to: category_thread_path(@conn, :index, @category) %></span>

lib/firestorm_web/web/templates/thread/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/firestorm_web/web/templates/thread/index.html.eex
<h2>Listing Threads</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for thread <- @threads do %>
    <tr>
      <td><%= thread.title %></td>

      <td class="text-right">
        <span><%= link "Show", to: category_thread_path(@conn, :show, @category, thread), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: category_thread_path(@conn, :edit, @category, thread), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: category_thread_path(@conn, :delete, @category, thread), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Thread", to: category_thread_path(@conn, :new, @category) %></span>

lib/firestorm_web/web/templates/thread/new.html.eex
<h2>Start a new thread</h2>

<%= form_for @changeset, category_thread_path(@conn, :create, @category), [class: "new-thread"], fn f -> %>
  <%= text_input f, :title, placeholder: "Type a title" %>
  <%= error_tag f, :title %>
  <%= textarea f, :body, placeholder: "Type thread content here. Use markdown syntax." %>
  <%= if Map.has_key?(@changeset.changes, :posts) do %>
    <%= error_tag hd(@changeset.changes.posts), :body %>
  <% end %>
  <div class="action-bar">
    <div class="begin">
    </div>
    <div class="end">
      <%= link "Cancel", to: category_path(@conn, :show, @category), class: "pure-button button-primary -muted cancel" %>
      <%= submit "Create Thread", class: "pure-button button-primary reply" %>
    </div>
  </div>
<% end %>

lib/firestorm_web/web/templates/thread/show.html.eex
<div class="thread-header">
  <h2><%= @thread.title %></h2>
  <div class="item-metadata">
    <%= link "@some_user", to: "#", class: "username" %>
    <%= @thread.inserted_at %>
  </div>
</div>

<ol class="post-list">
  <li><%= render "_first_post.html", post: @first_post, conn: @conn, category: @category, thread: @thread %></li>
  <%= for post <- @posts do %>
    <li>
      <%= render "_post.html", post: post, category: @category, thread: @thread, conn: @conn %>
    </li>
  <% end %>
</ol>

<span><%= link "Edit", to: category_thread_path(@conn, :edit, @category, @thread) %></span>
<span><%= link "Back", to: category_thread_path(@conn, :index, @category) %></span>