lib/firestorm_web/web/router.ex
defmodule FirestormWeb.Web.Router do
  use FirestormWeb.Web, :router

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", FirestormWeb.Web do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
    get "/logout", AuthController, :delete
  end

  scope "/", FirestormWeb.Web do
    pipe_through :browser # Use the default browser stack

    get "/", CategoryController, :index
    resources "/users", UserController
    resources "/categories", CategoryController do
      resources "/threads", ThreadController
    end
  end
end

lib/firestorm_web/web/views/layout_view.ex
defmodule FirestormWeb.Web.LayoutView do
  use FirestormWeb.Web, :view

  def js_script_tag do
    if Mix.env == :prod do
      "<script src=\"/js/app.js\"></script>"
    else
      "<script src=\"http://localhost:8080/js/app.js\"></script>"
    end
  end

  def css_link_tag do
    if Mix.env == :prod do
      "<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/app.css\" />"
    else
      "<link rel=\"stylesheet\" type=\"text/css\" href=\"http://localhost:8080/css/app.css\" />"
    end
  end
end

lib/firestorm_web/web/templates/layout/_drawer.html.eex
<ul>
  <%= if current_user(@conn) do %>
    <li><%= link "Log Out #{current_user(@conn).username}", to: auth_path(@conn, :delete) %></li>
  <% else %>
    <li><%= link "Log In", to: auth_path(@conn, :request, :github) %></li>
  <% end %>
</ul>

lib/firestorm_web/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- We obviously should have a decent title, for starters -->
    <title>Firestorm</title>
    <%= {:safe, css_link_tag()} %>
    <!-- We bring in fontawesome because it's awesome -->
    <script src="https://use.fontawesome.com/b706cffc0a.js"></script>
  </head>

  <!-- I'll add a layout-specific class to any layout I create -->
  <body class="layout-app">
    <!-- I'm using pure-drawer - http://mac81.github.io/pure-drawer/ - for a mobile navigation drawer -->
    <div class="pure-container" data-effect="pure-effect-slide">
      <input id="pure-toggle-right" class="pure-toggle" data-toggle="right" type="checkbox" />
      <label class="pure-toggle-label" data-toggle-label="right" for="pure-toggle-right">
        <span class="pure-toggle-icon"></span>
      </label>
      <div class="pure-drawer" data-position="right">
        <%= render "_drawer.html", conn: @conn %>
      </div>
      <!--
        this is the container for pure-drawer that holds the main content
        that the drawer will appear in front of
      -->
      <div class="pure-pusher-container">
        <!-- Stuff inside pure-pusher gets pushed if the drawer pushes content -->
        <div class="pure-pusher">
          any top navigation should go here
          <!-- Now our styles take over and we'll define the main content area -->
          <div class="layout-content">
            <div class="layout-drawer-tablet">
              <%= render "_drawer.html", conn: @conn %>
            </div>
            <!-- We made it to the main content! -->
            <div class="layout-content-main">
              <%= for {key, val} <- get_flash(@conn) do %>
                <p class="alert-box -<%= key %>" role="alert">
                  <%= val %>
                </p>
              <% end %>
              <!--
                And here's where we render a given view inside of the
                template
              -->
              <%= render @view_module, @view_template, assigns %>
            </div>
          </div>
        </div>
      </div>
      <!--
        Finally, this label will act as the overlay when it needs to appear
      -->
      <label class="pure-overlay" data-overlay="right" for="pure-toggle-right"></label>
    </div>
    <%= {:safe, js_script_tag()} %>
  </body>
</html>